### ISSUE TITLE
Chiarimento sulle condizioni di Luppolo

### ISSUE THREAD

**Issue by DiegoRosalio** [let-unimi/progetti#2]
## Espressioni booleane

Secondo la [sezione relativa alla sintassi](https://github.com/let-unimi/progetti/blob/master/05-Luppolo/Testo.md#il-linguaggio-luppolo) una condizione che contenga un *not* booleano (**!**) è valida solamente se è presente anche uno dei due operatori booleani *and* e *or*, **non** è perciò appartenente al linguaggio una condizione del tipo:

```
!<condizione>
```

È questa una peculiarità del linguaggio Luppolo o è un refuso della specifica?

## Valutazioni di chiamate

Sempre secondo la stessa sezione è possibile usare come condizione la chiamata a una funzione mentre nella [sezione relativa alla semantica](https://github.com/let-unimi/progetti/blob/master/05-Luppolo/Testo.md#la-semantica) è espressamente ribadito che:
> le condizioni possono pertanto risultare vere, o false, ma si ricorda che tali valori non sono tipi del linguaggio (pertanto, ad esempio, **non possono essere** assegnati ad una variabile, o **restituiti dalla valutazione di una chiamata di funzione**)."

Come si deve trattare l'espressione risultante da una chiamata a funzione usata in una condizione?

**Comment by mapio** [comment]
Si trattava di una mia svista, ho corretto testo (e versione precompilata). Grazie.

**Comment by mapio** [comment]
Scusa, avevo letto solo la prima parte. In realtà nel secondo caso la ragione è che potrebbe esistere una funzione di libreria che restituisce un valore booleano (ma non possono essere scritte funzioni in Luppolo che lo facciano).

In effetti è una "complicazione" abbastanza inutile, visto che al momento non sono previste funzioni di libreria che restituiscano valori booleani.

L'idea, ad esempio, è avere una funzione che dica se una espressione è un polinomio, o un monomio, o un numero razionale. Al momento, tali funzioni di libreria non sono previste, per cui puoi ignorare quella parte.

**Comment by DiegoRosalio** [comment]
D'accordo, grazie del chiarimento.
