### ISSUE TITLE
[Luppolo] test suite

### ISSUE THREAD

**Issue by Andreal2000** [let-unimi/progetti#4]
Apro questo issue per ricordarle di caricare la test suite di Luppolo.

**Comment by mapio** [comment]
Ho osservato (con Prog2) che le specifiche non sono sufficientemente precise da consentire di essere interpretate in modo del tutto non ambiguo (sopratutto rispetto alla semplificazione).

Per questa ragione, è sufficiente che il progetto produca risultati "ragionevoli" (ad esempio, almeno sugli esempi del testo). Non verrà testato in modo automatico su un ampio set di espressioni perché inevitabilmente possono presentarsi differenze (non significative, o comunque non indicative di bug).
