### ISSUE TITLE
[Luppolo] Possibile errore nel programma di esempio

### ISSUE THREAD

**Issue by mrSepi** [let-unimi/progetti#5]
Nel programma d'esempio presentato nella sezione [Il linguaggio luppolo](https://github.com/let-unimi/progetti/blob/master/05-Luppolo/Testo.md#il-linguaggio-luppolo)
nel caso in cui l'input sia 4 viene restituita l'espressione
$$x+x^{16}+4\cdot x^2+14\cdot x^4+18\cdot x^8 +1806$$
quando invece mi sembra che il coefficiente corretto di $x^8$ dovrebbe essere $26$

**Comment by oscar1888** [comment]
Il risultato della consegna dovrebbe essere giusto, poiché ogni iterato del costrutto `foreach` lavora su un addendo **non** espanso.

Più specificamente: dopo l'esecuzione della terza iterazione del ciclo `repeat`, `Result` ha valore $x+{({x}^{2})}^{2}+{({({x}^{2})}^{2})}^{2}+{(2 \\cdot {x}^{2})}^{2}+3 \\cdot {x}^{2}+42$ (chiamiamo questa espressione $\alpha$). Volendo seguire il flusso di esecuzione, se ad $\alpha$ si somma una espressione pari alla somma dei quadrati dei suoi addendi (espressione ottenuta dalla chiamata a `SquareTerms`) e si effettua una espansione sul risultato ottenuto (chiamata a `Expand` nel `return` della funzione `Main`), si ottiene l'espressione descritta nella consegna.

D'altra parte, il coefficiente $26$ verrebbe solamente se si elevano al quadrato gli addendi della somma **espansa** in `SquareTerms`. Infatti, se si parte con `Result` che ha valore pari all'espansione di $\alpha$ (cioè $x+{x}^{8}+3 \\cdot {x}^{2}+5 \\cdot {x}^{4}+42$) dopo la terza iterazione del ciclo `repeat`, si somma il risultato della chiamata a `SquareTerms` e si espande il risultato finale, si ottiene $x+{x}^{16}+4 \\cdot {x}^{2}+14 \\cdot {x}^{4}+26 \\cdot {x}^{8}+1806$. Questo comportamento si può ottenere espandendo gli output forniti da `SquareTerms`.

**Comment by mapio** [comment]
Mi pare che il suo collega abbia ragione. Se non è convinto, domani provo a rieseguire i conti con la mia soluzione e stampare il risultato ad ogni iterato.

**Comment by mrSepi** [comment]
Grazie per il chiarimento.
