### ISSUE TITLE
[Luppolo] Precedenza operatori

### ISSUE THREAD

**Issue by mrSepi** [let-unimi/progetti#6]
Nella sezione [Una nota sulle espressioni e condizioni](https://github.com/let-unimi/progetti/blob/master/05-Luppolo/Testo.md#una-nota-sulle-espressioni-e-condizioni) viene specificato che il `*` e `/` devono avere precedenza su `+` e `-` unari.

In questo modo però ad esempio l'espressione `2^-3*8` verrebbe valutata in `2^-24`, quando invece altri linguaggi di programmazione (come Python) o programmi di calcolo danno la precedenza agli operatori unari.

**Comment by mapio** [comment]
L'espressione `2^-3*8` posto che l'elevamento a potenza ha la precedenza più alta rispetto agli altri operatori (binari), ma non rispetto al `-` unario, equivale a `(2^-3) * 8` che vale `1.0`. Mi pare sia esattamente il valore che si ottiene con Python per l'espressione `2**-3*8`.

**Comment by mrSepi** [comment]
Mi scusi, avevo fatto confusione.
Grazie.
